### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by joshua1** [timeshift92/hasura-orm#3]
Hi  @timeshift92 . I wanted to find out if this lib handles GraphQL subscriptions , especially when paired with graphql-svelte

**Comment by timeshift92** [comment]
Hello, yes, https://github.com/timeshift92/sapper-hasura/blob/main/src/core/svqlConfig.ts
This link give you new config with graphql-svelte

**Comment by timeshift92** [comment]
'''
export default function hasura(schema) {
	Hasura.provider = client;
	const orm = new Hasura(schema)
	orm.provider = client;
	return orm;
}

**Comment by joshua1** [comment]
Thanks @timeshift92
