### ISSUE TITLE
Hasura constructor and public properties (readme update?)

### ISSUE THREAD

**Issue by joshua1** [timeshift92/hasura-orm#4]
Hi @timeshift92 , it seems like the code in the readme needs updating .The Hasura class has a constructor that takes an object (instead of just the schema specified in the hasura function). Also properties like provider are no longer public but protected. This might mean readme update ?

**Comment by timeshift92** [comment]
Hello, I haven't updated it for a long time, I will update it soon

**Comment by timeshift92** [comment]
updated, take a look
