### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by joshua1** [timeshift92/hasura-orm#5]
Hi @timeshift92  can you extend the documentation/readme to at least show how to do insert, update , delete and subscribe. I have been going through the code trying to figure out how to do an insert using things like hasura('schema').insert(payload), which returns an Insert object. do i call mutate afterwards or what . i need to figure out how to do an insert and also specify what to return afterwards (id, or whole object). I will appreciate it if i get a reply from you around this ASAP . Thanks

**Comment by timeshift92** [comment]
updated, take a look
